USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE WAREHOUSE PRODUCT_MATCHING_DS_WH; --by default, this creates an XS Standard Warehouse
CREATE OR REPLACE DATABASE PRODUCT_MATCHING_DB;
CREATE OR REPLACE SCHEMA MATCH;
USE WAREHOUSE PRODUCT_MATCHING_DS_WH;
USE DATABASE PRODUCT_MATCHING_DB;
USE SCHEMA MATCH;
CREATE OR REPLACE STAGE MODEL DIRECTORY=(ENABLE=true); --to store semantic model for the chatbot

CREATE OR REPLACE ROLE PRODUCT_MATCHING_DATA_ANALYST;
SET my_user_var = (SELECT  '"' || CURRENT_USER() || '"' );

-- Grant role to current user
GRANT ROLE PRODUCT_MATCHING_DATA_ANALYST TO USER identifier($my_user_var);

GRANT ALL ON DATABASE PRODUCT_MATCHING_DB TO ROLE PRODUCT_MATCHING_DATA_ANALYST;
GRANT ALL ON SCHEMA PRODUCT_MATCHING_DB.MATCH TO ROLE PRODUCT_MATCHING_DATA_ANALYST;
GRANT ALL ON WAREHOUSE PRODUCT_MATCHING_WH TO ROLE PRODUCT_MATCHING_DATA_ANALYST;
GRANT READ, WRITE ON STAGE PRODUCT_MATCHING_DB.MATCH.MODEL TO ROLE PRODUCT_MATCHING_DATA_ANALYST;
